### ISSUE TITLE
pixels.h not found

### ISSUE THREAD

**Issue by TekConsult** [HomeSpan/HolidayLights#1]
Hi,
great project! I want to try your code, but can't find the pixels library.
Where can I get the pixels library?

kind regards 
Markus

**Comment by HomeSpan** [comment]
It's in the latest version I'm releasing today.  Will be available in a few hours.

**Comment by HomeSpan** [comment]
HomeSpan version 1.5.0 has just been released and includes the new **Pixel()** class used in this project.
